# Generated by Django 2.1.4 on 2018-12-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=128)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='Recruit',
        ),
    ]
